feat: Impl ROM Read
ofuton-dev/n64emu pull request #7
Opened 2020-11-03 15:16 UTC by kamiyaowl

.n64, .z64, .v64 fileを読み込んでHeaderを展開する実装を入れました。
どうやらendian, byteswapが形式によってバラバラのようですが [Reddit](https://www.reddit.com/r/emulation/comments/7hrvzp/the_three_different_n64_rom_formats_explained_for/?st=jn9t30t4&sh=1951de19) を参考に変換する機能を実装しているので対応できるはずです。

入れてない実装は以下です
* Bus Masterから展開されたデータを読み出す機能
  * 私もMemoryMapまわりを把握できていないのでこのリサーチと、Bus I/F周りが落ち着くまで後回し
* CRC検査
  * ひとまず後回し。Boot Process上必須なら優先して実装する必要がありそうです

main.goからも指定できるようにしておきました
```
$ go run ./cmd/ ./CPUADD.N64 
ROM ImageName='CPU TEST CPU ADD    '
Hello n64emu!
```

2020-11-03 15:46 UTC, kamiyaowl commented
> * Bus Masterから展開されたデータを読み出す機能
>   * 私もMemoryMapまわりを把握できていないのでこのリサーチと、Bus I/F周りが落ち着くまで後回し

まだサラッとしか読めてませんがBoot Processの途中で Game Pak -> RDRAM Copyしているのかな。
とすると、Bus MasterはCPUではなくDMACみたいですね。 
http://en64.shoutwiki.com/wiki/N64_Memory#PI_(Parallel_Interface)

2020-11-03 16:27 UTC, bokuweb approved these changes
👍

2020-11-03 18:41 UTC, pokemium requested changes
Goのスライスは配列本体をポインタとして持ってるので、引数で渡すときはスライスのポインタではなく、スライスをそのまま渡してもいいかなと思います！

2020-11-03 20:14 UTC, kamiyaowl commented
reviewありがとうございます！
なるほど、同じ懸念があったのでsliceのポインタで取り回していましたが、サイズを変える用途でなければ特に気にしなくて良い感じなのですね。
後で修正しておきます:sunglasses:

https://twitter.com/kamiya_owl/status/1323622691903959040?s=19

2020-11-03 20:30 UTC, kamiyaowl commented
あとは #8 を見ていて気づきましたが `pkg/types` を使った定義に直したほうが良さそうですね

2020-11-04 09:30 UTC, bokuweb commented
> あとは #8 を見ていて気づきましたが pkg/types を使った定義に直したほうが良さそうですね

これは結構個人的な好みの話でもあるのでやりすぎ感があったら言ってください。場合によっては`uintX`に戻せばいいと思います。個人的にはエミュ作るときはJSでも `type Word = number`とかしちゃう人間なので。。。

2020-11-04 14:27 UTC, kamiyaowl commented
> Goのスライスは配列本体をポインタとして持ってるので、引数で渡すときはスライスのポインタではなく、スライスをそのまま渡してもいいかなと思います！(appendするときはポインタ自体が変化するので事情が変わりますが今回のケースでは問題ないはずです)
> 
> ```go
> // https://github.com/golang/go/blob/846dce9d05f19a1f53465e62a304dea21b99f910/src/runtime/slice.go
> type slice struct {
> 	array unsafe.Pointer
> 	len   int
> 	cap   int
> }
> ```

https://github.com/ofuton-dev/n64emu/pull/7/commits/d229bf4730dd4b28c02658f0745289b00c71e643 で修正しました。

ビルドできること、既存のテストが落ちないことはCI含め確認済です。

2020-11-04 20:39 UTC, pokemium approved these changes

2020-11-05 14:52 UTC, kamiyaowl reviewed
`binary.BigEndian.{Uint32, Uint16}` を使うようにしただけですので、再reviewは出さずにmergeします。

(code reviewのコストもあると思いますので、設計にあまり影響のないminor fixは反映しやすくしたいと思っています...)

2020-11-05 14:53 UTC, merged